# fly.toml app configuration file generated for sync-server on 2023-09-29T10:09:34-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sync-server"
primary_region = "iad"
kill_timeout = 60

[env]
  PORT = "9000"
  NODE_ENV = "production"

[build]

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    hard_limit = 1000
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"

[deploy]
  strategy = "bluegreen"
